fastify/busboy

- deps/dicer/bench/dicer-bench-multipart-parser.js
We need to increase the benchmark rounds to 10 to get realistic benchmarks. After 4 rounds it optimizes for maximum speed.
```
uzlopak@uzlopak-Lenovo-Legion-5-17ARH05H:~/Workspace/fastify/busboy$ npm run bench:dicer
> @fastify/busboy@1.0.0 bench:dicer
> node deps/dicer/bench/dicer-bench-multipart-parser.js
1515.15 mb/sec
1351.35 mb/sec
1333.33 mb/sec
2127.66 mb/sec
2127.66 mb/sec
2127.66 mb/sec
2127.66 mb/sec
2127.66 mb/sec
2173.91 mb/sec
2127.66 mb/sec
```
> increase benchmark rounds to 10

- deps/dicer/lib/Dicer.js
- deps/dicer/lib/HeaderParser.js
- deps/streamsearch/sbmh.js
- package.json
- test/streamsearch.spec.js
This PR integrates Searchstream package into busboy.
It also uses now Buffer.from and Buffer.allocate instead of the old constructor notation.
I also wrote unit tests for it. Seems I missed two branches.
I think the real bottle neck is this piece of code. 
The original searchstream was made for node 0.8.0. So it does not use anything which could improve the performance. The hottest parts are actually these lines
We need either optimize searchstream or replace it with a modern solution. 
By simply replacing the jsmemcmp function with Buffer.compare (which didnt exist for node 0.8.0 the benchmark looks like this:
```
> @fastify/busboy@1.0.0 bench:dicer
> node deps/dicer/bench/dicer-bench-multipart-parser.js
2500.00 mb/sec
2272.73 mb/sec
2222.22 mb/sec
3846.15 mb/sec
4000.00 mb/sec
4000.00 …
```
> Integrate SearchStream

- test/streamsearch.spec.js
With this PR the test coverage of sbmh.js increases to
sbmh.js             |   95.09 |    87.03 |     100 |   94.94 
in concert with the other tests:
sbmh.js             |   98.03 |    92.59 |     100 |   97.97
Tbh, i dont know how to increase it further, as i quite dont get in which cases the other branches get hit. 
> Improve code coverage for searchstream

- deps/streamsearch/sbmh.js
This should improve the performance of searchstream
before:
```
> @fastify/busboy@1.0.0 bench:dicer
> node deps/dicer/bench/dicer-bench-multipart-parser.js
2380.95 mb/sec
2325.58 mb/sec
2272.73 mb/sec
3703.70 mb/sec
3571.43 mb/sec
3703.70 mb/sec
3703.70 mb/sec
3571.43 mb/sec
3571.43 mb/sec
3571.43 mb/sec
```
after:
```
> @fastify/busboy@1.0.0 bench:dicer
> node deps/dicer/bench/dicer-bench-multipart-parser.js
2564.10 mb/sec
2222.22 mb/sec
2173.91 mb/sec
4000.00 mb/sec
4000.00 mb/sec
4000.00 mb/sec
4000.00 mb/sec
4000.00 mb/sec
4000.00 mb/sec
4000.00 mb/sec
```
> replace jsmemcmp with Buffer.compare

- deps/dicer/lib/Dicer.js
According to deoptigate, there are two inline caching issues.
This one fixes one of them.
> fix inline caching deoptimization

- deps/streamsearch/sbmh.js
Unit tests are green, so I think the change provides an equivalent change. 
Benchmark: 
```
> @fastify/busboy@1.0.0 bench:dicer
> node deps/dicer/bench/dicer-bench-multipart-parser.js
9090.91 mb/sec
11111.11 mb/sec
10000.00 mb/sec
11111.11 mb/sec
11111.11 mb/sec
11111.11 mb/sec
12500.00 mb/sec
12500.00 mb/sec
11111.11 mb/sec
11111.11 mb/sec
```
> Improve performance in searchstream

- deps/dicer/lib/Dicer.js
- deps/dicer/lib/HeaderParser.js
- test/dicer-malformed-header.spec.js
This adapts the bugfix and improvements from @RolandHeinze
https://github.com/mscdex/dicer/pull/22
To see that the bug exists you have to checkout the commit "fix malformed header bug, red phase", which is prepatched phase with added unit test.
Afterwards the above patch was adapted to the codebase in "fix malformed header bug, green phase". The unit test is then green.
> Fix Malformed header bug

- deps/encoding/TextDecoder.js
- lib/utils.js
Removing Encoders as we dont need them. Increasing the test coverage...
Rename encodings.js to TextDecoder.js as it is the main purpose of this file.
add hasEncoding for potentially faster lookup if encoding exists
> Remove Encoders

- .eslintrc.js
- deps/dicer/lib/HeaderParser.js
- deps/encoding/TextDecoder.js
- deps/streamsearch/sbmh.js
- lib/main.js
- lib/types/multipart.js
- lib/types/urlencoded.js
- lib/utils.js
- package.json
- test/dicer-multipart-extra-trailer.spec.js
- test/dicer-multipart-nolisteners.spec.js
- test/dicer-multipart.spec.js
This PR is also for discussing  if we should switch to standardjs, like fastify core.
This PR adds all the changes, which need to be done manually to be conform with standardjs. It is easier to review the changes, which have to be done manually before doing a lint:fix, than doing a lint:fix and then fixing manually the stuff, which standardjs could not handle. 
I excluded deps/encoding as it is kind of a standalone part and messing with it is potentially critical. Also encoding-indexes.js is a huge file, so having it in a "compressed" format makes sense. 
So if we agree on using standardjs like fastify core does, we should merge this, and in a second PR we would just run `npm run lint:fix` and changing to standard for `npm run lint` in package.json.Also dont forget to add standard to …
> add standard and prepare for standard lint

- .eslintrc.js
- README.md
- bench/busboy-bench.js
- bench/dicer/dicer-bench-multipart-parser.js
- bench/fastify-busboy-bench.js
- deps/dicer/lib/Dicer.js
- deps/dicer/lib/HeaderParser.js
- deps/dicer/lib/PartStream.js
- deps/streamsearch/sbmh.js
- lib/main.js
- lib/types/multipart.js
- lib/types/urlencoded.js
- lib/utils.js
- package.json
- test/decoder.spec.js
- test/dicer-endfinish.spec.js
- test/dicer-headerparser.spec.js
- test/dicer-malformed-header.spec.js
- test/dicer-multipart-extra-trailer.spec.js
- test/dicer-multipart-nolisteners.spec.js
- test/dicer-multipart.spec.js
- test/get-limit.spec.js
- test/multipart-stream-pause.spec.js
- test/parse-params.spec.js
- test/streamsearch.spec.js
- test/types-multipart.spec.js
- test/types-urlencoded.spec.js
This PR consists of three commits:
1. activate standard in project configuration
2. run the standard fixer
3. add button to Readme.md
> Enforce standard

- CHANGELOG.md
- MIGRATING.md
- README.md
- lib/main.d.ts
- lib/main.js
- lib/types/multipart.js
- test/types-multipart.spec.js
- test/types/main.test-d.ts
I think this handles the issue with blob uploads correctly:
It doesnt matter we have set a filename or not. We just check if the content is an octet stream. If so we treat it as a file. If not, we treat it as a field. 
Also according to the Spec, a filename is not mandatory.
https://datatracker.ietf.org/doc/html/rfc7578#section-4.2
```
For form data that represents the content of a file, a name for the
file SHOULD be supplied as well, by using a "filename" parameter of
the Content-Disposition header field.  The file name isn't mandatory
for cases where the file name isn't available or is meaningless or
private; this might result, for example, when selection or drag-and-
drop is used or when the form data content is streamed directly from
a device.
```
So the check if filename was not …
> handle blobs as fields

- CHANGELOG.md
- deps/dicer/lib/Dicer.js
- test/dicer-endfinish.spec.js
- test/dicer-headerparser.spec.js
- test/multipart-stream-pause.spec.js
- test/types-multipart.spec.js
- test/types-urlencoded.spec.js
@ruur
@kibertoad 
Lets talk about the empty part bug here.
I use a simpler test than in the original PR. As you can see, it doesnt throw an error, despite it should throw an "Uncaught AssertionError: Parsed result count mismatch. Saw 4. Expected: 3: expected 4 to deeply equal 3"
If you uncomment the part in Dicer.js, you will see that it will then throw the expected AssertionError. Then you uncomment that line in the unit test, and it will become green.
I could not create a red phase, because it is like @ruur described hanging. So if you confirm @kibertoad  I would uncomment the commented out codes, and we should merge it.
> fix empty part bug, 2nd try

- CHANGELOG.md
- README.md
- deps/dicer/lib/HeaderParser.js
- lib/main.d.ts
- lib/types/multipart.js
- test/dicer-headerparser.spec.js
- test/types/main.test-d.ts
According to the comments, the maxHeaderSize should be actually be corresponding to the node http modules maxHeaderSize value. But it is actually wrong, as the default maxHeaderSize is and was always 8 kb and not 80 kb. On the other hand, the header of a request is different than the header of a multipart. 
With this PR we expose headerSize as configurable limit.  So if somebody wants to reduce the allowed size of a header, it is now possible to set the limit. 
This PR is non-breaking, as the original 80 kbytes are still enforced. Maybe we should inform in a security part of the readme.md that we recommend to reduce the header size to something smaller. 
> introduce headerSize limit

- lib/utils.js
As there is a lot of test for `str[i]` value in this loop, keeping the value in a separated variable is faster.
Sidenote: `bench:busboy` script is not working.
> feat: improve array parse performances

- CHANGELOG.md
- deps/dicer/lib/HeaderParser.js
- test/dicer-headerparser.spec.js
tl;dr;
An attacker could send a payload with large headers, which contain no colon, repeatedly, resulting in a REDoS-Attack. 
The Regex for handling headerpairs is prone to catastrophic backtracking. 
This is even more critical, as busboys default limit for multipart headers is 80kby and that if a header is not valid, the counter for headers is not increasing. Meaning, that the attacker could send a big payload of multipart formdata, were each multipart contains 80kby of invalid headerdata resulting in a DoS-Attack.
To avoid this, we just check if the line contains a colon and if so ensure that it is not at the first position. If not we exit early. If not we can savely use the Regex for the header as before.
and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_C …
> Fix potential ReDOS-Attack-Vector in Headerparser

- README.md
Make benchmark results monospaced so they align vertically and are easier to compare.
> Make benchmark results monospaced

- .github/workflows/ci.yml
- README.md
- lib/main.js
- lib/types/multipart.js
- test/dicer-endfinish.spec.js
BREAKING CHANGE: drops support for node 10, 12, and 17; adds support for node 18
> ci!: migrate to reusable workflow

- lib/types/multipart.js
Should fix https://github.com/fastify/fastify-multipart/issues/315
> handle unpipeing, cancelling or destroying of busboy accordingly

- .eslintrc.js
- package.json
`eslint-plugin-node` is no longer maintained.
Main repo migrated a while back:
https://github.com/fastify/fastify/blob/67bee117a7c5c6dad503f656204e49cf329a37af/package.json#L144
> build(deps-dev): replace eslint-plugin-node with eslint-plugin-n

- benchmarks/busboy/contestants/busboy.js
Fixes the benchmarks, the original Busboy cannot be initialized with `new`
> fix: busboy cannot be initialized with `new`

- lib/utils/decodeText.js
- package.json
This was added in #50 for reasons I don't really understand. According to the PR node's TextDecoder is the fastest (and I assume it's even faster now), provides the same features, and is available globally since node v11.
> remove text-decoding

- README.md
- bench/dicer/multiparty-bench-multipart-parser.js
- bench/dicer/parted-bench-multipart-parser.js
- bench/dicer/parted-multipart.js
- benchmarks/common/resultsCombinator.js
- deps/dicer/lib/Dicer.js
- deps/dicer/lib/HeaderParser.js
- deps/dicer/lib/PartStream.js
- deps/streamsearch/sbmh.js
- lib/main.js
- lib/types/multipart.js
- test/dicer-multipart-extra-trailer.spec.js
- test/dicer-multipart-nolisteners.spec.js
- test/dicer-multipart.spec.js
- test/multipart-stream-pause.spec.js
- test/parse-params.spec.js
- test/types-multipart.spec.js
- test/types-urlencoded.spec.js
See https://github.com/fastify/fastify-static/pull/407
> perf: use `node:` prefix to bypass require.cache call for builtins

- bench/busboy-form-bench-latin1.js
- bench/busboy-form-bench-utf8.js
- bench/createMultipartBufferForEncodingBench.js
- bench/dicer/dicer-bench-multipart-parser.js
- bench/dicer/formidable-bench-multipart-parser.js
- bench/dicer/multipartser-bench-multipart-parser.js
- bench/dicer/multiparty-bench-multipart-parser.js
- bench/dicer/parted-bench-multipart-parser.js
- bench/dicer/parted-multipart.js
- bench/fastify-busboy-form-bench-latin1.js
- bench/fastify-busboy-form-bench-utf8.js
- benchmarks/busboy/contestants/busboy.js
- benchmarks/busboy/contestants/fastify-busboy.js
- benchmarks/busboy/data.js
- benchmarks/busboy/executioner.js
- benchmarks/busboy/validator.js
- benchmarks/common/commonBuilder.js
- benchmarks/common/contestantResolver.js
- benchmarks/common/executionUtils.js
- benchmarks/common/resultUtils.js
- benchmarks/common/resultsCombinator.js
> chore: add missing `use strict` directives

- lib/utils/decodeText.js
The script either missed this or the change was made after it ran
For consistency purposes
> chore: remove unused error

- deps/streamsearch/sbmh.js
Goal: Modernize and improve this library as much possible starting with StreamSearch
Small improvements:
https://github.com/fastify/busboy/commit/a4e91c508f61dc45f8507e689280e51380a67317 — when we match, no need to calculate the pos again, let's just directly assign and check
https://github.com/fastify/busboy/commit/c281addf88a4f701af71f28d309fe802a8b23a70 — unnecessary allocation
https://github.com/fastify/busboy/commit/ca4602dc1f93ebb130b24ccdc92590b13eaffc01 — unnecessary subtraction
> perf: refactor parts of StreamSearch
